### ISSUE TITLE
Autoprefixer not working on different webpack syntax

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/banner#20]
Tried this, but didn't work. Can you take a quick look, @brenoc? 
```javascript
 {
        test: /\.scss$/,
        loaders: production ?
          ['style', 'css', 'autoprefixer?browsers=last 2 version', 'sass'] :
          ['style', 'css?sourceMap', 'sass?sourceMap']
      },
```

**Comment by dfosco** [comment]
Oh, it's running on branch `feature/autoprefixer`, by the way.

**Comment by brenoc** [comment]
@dfosco Check:
https://github.com/vtex-apps/editor/pull/54/files

You're missing a devDependency

**Comment by dfosco** [comment]
@brenoc For the banner? They're [here](https://github.com/vtex-apps/banner/blob/feature/autoprefixer/package.json):

```json
  "devDependencies": {
    "autoprefixer": "^6.1.2",
    "autoprefixer-loader": "^3.1.0",
```
