### ISSUE TITLE
Controlling image size

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/banner#24]
@brenoc @tamorim @bellacorbo How do we control image size? I'm currently cropping the bottom of the banner image on some viewport sizes to keep it from overflowing and getting too large in height.

It will serve for now as long as the user uploads images that are not too tall, but we should either lock image upload on the editor or process the image somehow before serving it. Any ideas?

cc @amoreira

**Comment by brenoc** [comment]
We can crop the image using canvas (HTML5 feature):
http://roadmanfong.github.io/react-cropper/example/

**Comment by brenoc** [comment]
We can use it on the editor before uploading the image.

**Comment by brenoc** [comment]
Hey, I think issues #6 and #22 already concern that. I'll close this issue.
